flowers: 
        .byte $8A,$28,$A0
        .byte $2A,$22,$A2
        .byte $A6,$A2,$22
        .byte $95,$9A,$2A
        .byte $A5,$5A,$AA
        .byte $A9,$6A,$2A
        .byte $A6,$08,$0A
        .byte $AA,$00,$22
        .byte $8A,$82,$0A
        .byte $8A,$82,$AA
        .byte $28,$80,$AA
        .byte $A0,$20,$A2
        .byte $A2,$20,$80
        .byte $28,$A0,$00
        .byte $8A,$A8,$22
        .byte $A8,$88,$2A
;	defblock 48,$00
leaf1: 
        .byte $82,$82,$AA
        .byte $00,$8A,$02
        .byte $00,$A8,$00
        .byte $20,$20,$08
        .byte $A8,$20,$2A
        .byte $AA,$20,$2A
        .byte $AA,$08,$A0
        .byte $82,$02,$80
        .byte $00,$02,$00
        .byte $02,$02,$02
        .byte $0A,$00,$0A
        .byte $0A,$00,$A2
        .byte $AA,$82,$80
        .byte $A0,$82,$08
        .byte $A0,$02,$2A
        .byte $8A,$00,$2A
;	defblock 48,$00
leaf2: 
        .byte $A2,$02,$AA
        .byte $84,$82,$8A
        .byte $11,$82,$12
        .byte $A2,$80,$44
        .byte $AA,$A0,$8A
        .byte $AA,$A0,$AA
        .byte $A8,$A0,$AA
        .byte $A1,$00,$8A
        .byte $84,$82,$1A
        .byte $AA,$82,$86
        .byte $8A,$82,$AA
        .byte $12,$82,$AA
        .byte $84,$02,$2A
        .byte $A2,$00,$12
        .byte $AA,$0A,$4A
        .byte $AA,$0A,$AA
;	defblock 48,$00
flowers2: 
        .byte $8A,$28,$A0
        .byte $2A,$22,$A2
        .byte $A6,$A2,$22
        .byte $9D,$9A,$2A
        .byte $A7,$DA,$AA
        .byte $AB,$E9,$A6
        .byte $A6,$0B,$DD
        .byte $AA,$00,$F6
        .byte $8A,$82,$6A
        .byte $8A,$82,$AA
        .byte $28,$80,$AA
        .byte $A7,$20,$A2
        .byte $AD,$20,$80
        .byte $28,$A0,$00
        .byte $8A,$A8,$22
        .byte $A8,$88,$2A
;	defblock 48,$00
leaf6: 
        .byte $A0,$AA,$AA
        .byte $80,$28,$0A
        .byte $80,$20,$00
        .byte $0A,$20,$00
        .byte $2A,$02,$A2
        .byte $A0,$02,$AA
        .byte $82,$00,$2A
        .byte $8A,$0A,$0A
        .byte $AA,$0A,$AA
        .byte $A2,$82,$AA
        .byte $8A,$A0,$A2
        .byte $8A,$A0,$A8
        .byte $02,$A8,$28
        .byte $82,$A0,$2A
        .byte $02,$80,$AA
        .byte $0A,$8A,$A8
;	defblock 48,$00
leaf4: 
        .byte $A2,$BA,$A2
        .byte $A2,$DE,$82
        .byte $28,$BA,$80
        .byte $28,$AA,$08
        .byte $0A,$0A,$08
        .byte $02,$A0,$20
        .byte $20,$A2,$08
        .byte $20,$0A,$20
        .byte $08,$02,$00
        .byte $22,$82,$82
        .byte $02,$00,$A2
        .byte $0A,$20,$0A
        .byte $00,$80,$A2
        .byte $80,$80,$A8
        .byte $A0,$02,$A8
        .byte $AA,$0A,$A2
;	defblock 48,$00
flowers3: 
        .byte $AA,$AA,$AA
        .byte $AA,$AE,$AA
        .byte $AA,$BF,$A8
        .byte $8A,$AE,$AA
        .byte $AA,$A2,$AA
        .byte $AA,$82,$2A
        .byte $AA,$A0,$AA
        .byte $AE,$A2,$A6
        .byte $BF,$AA,$8A
        .byte $AE,$AA,$AA
        .byte $82,$AA,$EA
        .byte $A0,$AB,$FA
        .byte $A2,$AA,$EA
        .byte $8A,$A8,$2A
        .byte $AA,$AA,$0A
        .byte $AA,$2A,$2A
;	defblock 48,$00
leaf5: 
        .byte $AA,$0A,$80
        .byte $5A,$82,$02
        .byte $95,$AA,$02
        .byte $A5,$5A,$8A
        .byte $A5,$55,$8A
        .byte $A9,$55,$60
        .byte $8A,$95,$6A
        .byte $00,$AA,$5A
        .byte $00,$AA,$9A
        .byte $80,$16,$95
        .byte $A0,$25,$9A
        .byte $AA,$0A,$6A
        .byte $AA,$8A,$68
        .byte $A8,$0A,$68
        .byte $A2,$A2,$62
        .byte $8A,$A8,$0A
;	defblock 48,$00
leaf3: 
        .byte $80,$2A,$0A
        .byte $80,$0A,$82
        .byte $80,$A2,$A0
        .byte $02,$A5,$A0
        .byte $02,$A0,$A8
        .byte $02,$A5,$AA
        .byte $00,$AA,$AA
        .byte $80,$AA,$AA
        .byte $80,$82,$AA
        .byte $80,$00,$2A
        .byte $80,$08,$8A
        .byte $A0,$2A,$9A
        .byte $80,$AA,$02
        .byte $80,$AA,$56
        .byte $82,$AA,$8A
        .byte $80,$AA,$AA
;	defblock 48,$00

; exit --------------------------

exit1:
        .byte $AA,$96,$A2
        .byte $89,$69,$68
        .byte $26,$BE,$98
        .byte $9B,$BA,$E6
        .byte $7B,$FE,$FD
        .byte $7B,$BF,$ED
        .byte $7F,$AE,$ED
        .byte $7B,$BE,$ED
        .byte $7B,$FE,$FD
        .byte $7B,$BF,$ED
        .byte $7F,$BA,$ED
        .byte $7B,$BE,$ED
        .byte $7B,$AF,$FD
        .byte $7B,$EE,$ED
        .byte $6A,$AA,$A9
        .byte $55,$55,$55
;	defblock 48,$00
exit2:
        .byte $AA,$96,$A2
        .byte $89,$69,$68
        .byte $26,$AA,$98
        .byte $9A,$AA,$A6
        .byte $6A,$AA,$A9
        .byte $6A,$AA,$A9
        .byte $6A,$AA,$A9
        .byte $6A,$AA,$A9
        .byte $6A,$AA,$A9
        .byte $6A,$65,$A9
        .byte $6A,$AA,$A9
        .byte $69,$96,$69
        .byte $6A,$AA,$A9
        .byte $65,$55,$59
        .byte $6A,$AA,$A9
        .byte $55,$55,$55
;	defblock 48,$00

; Final exit --------------------

finalexit1:
        .byte $82,$12,$51
        .byte $4D,$18,$58
        .byte $B7,$44,$A2
        .byte $4E,$46,$2A
        .byte $05,$1A,$AA
        .byte $16,$6A,$A8
        .byte $04,$6A,$8A
        .byte $80,$AA,$AA
        .byte $50,$A2,$AA
        .byte $42,$A8,$AA
        .byte $24,$AA,$AA
        .byte $96,$EA,$A6
        .byte $15,$A8,$AA
        .byte $02,$6A,$82
        .byte $80,$4A,$68
        .byte $68,$66,$A8
;	defblock 48,$00
finalexit2:
        .byte $14,$78,$61
        .byte $29,$DD,$01
        .byte $AA,$B2,$55
        .byte $A2,$89,$18
        .byte $AA,$AB,$85
        .byte $8A,$AA,$52
        .byte $AA,$8A,$81
        .byte $AA,$AA,$10
        .byte $AA,$AA,$95
        .byte $AA,$88,$94
        .byte $AA,$AA,$82
        .byte $A6,$AA,$96
        .byte $2A,$AA,$1D
        .byte $AA,$29,$77
        .byte $A4,$A5,$4C
        .byte $AA,$99,$01
;	defblock 48,$00

